import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// Removed Metadata type as JavaScript doesn't support type annotations
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Removed TypeScript type annotations for props
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
